version: "3"
services:
  backend:
    build: ./backend
    ports: 
      - 3000:3000
    environment:
      - PORT=3000
    volumes:
      - ./backend:/home/app
      - '/home/app/node_modules'
    expose:
      - 3000
  frontend:
    build: ./frontend
    ports: 
      - 80:80
    environment:
      - PORT=80
    volumes:
      - ./frontend:/home/app
      - '/home/app/node_modules'
    tty: true